/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-11-29 at 02:10:19 UTC 
 * Modify at your own risk.
 */

package com.example.giveaway.posteditemendpoint;

/**
 * Service definition for Posteditemendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PosteditemendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Posteditemendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the posteditemendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://giveawayprealpha.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "posteditemendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Posteditemendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Posteditemendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPostedItem".
   *
   * This request holds the parameters needed by the the posteditemendpoint server.  After setting any
   * optional parameters, call the {@link GetPostedItem#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetPostedItem getPostedItem(java.lang.Long id) throws java.io.IOException {
    GetPostedItem result = new GetPostedItem(id);
    initialize(result);
    return result;
  }

  public class GetPostedItem extends PosteditemendpointRequest<com.example.giveaway.posteditemendpoint.model.PostedItem> {

    private static final String REST_PATH = "posteditem/{id}";

    /**
     * Create a request for the method "getPostedItem".
     *
     * This request holds the parameters needed by the the posteditemendpoint server.  After setting
     * any optional parameters, call the {@link GetPostedItem#execute()} method to invoke the remote
     * operation. <p> {@link GetPostedItem#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPostedItem(java.lang.Long id) {
      super(Posteditemendpoint.this, "GET", REST_PATH, null, com.example.giveaway.posteditemendpoint.model.PostedItem.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPostedItem setAlt(java.lang.String alt) {
      return (GetPostedItem) super.setAlt(alt);
    }

    @Override
    public GetPostedItem setFields(java.lang.String fields) {
      return (GetPostedItem) super.setFields(fields);
    }

    @Override
    public GetPostedItem setKey(java.lang.String key) {
      return (GetPostedItem) super.setKey(key);
    }

    @Override
    public GetPostedItem setOauthToken(java.lang.String oauthToken) {
      return (GetPostedItem) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPostedItem setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPostedItem) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPostedItem setQuotaUser(java.lang.String quotaUser) {
      return (GetPostedItem) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPostedItem setUserIp(java.lang.String userIp) {
      return (GetPostedItem) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPostedItem setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPostedItem set(String parameterName, Object value) {
      return (GetPostedItem) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPostedItem".
   *
   * This request holds the parameters needed by the the posteditemendpoint server.  After setting any
   * optional parameters, call the {@link InsertPostedItem#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.giveaway.posteditemendpoint.model.PostedItem}
   * @return the request
   */
  public InsertPostedItem insertPostedItem(com.example.giveaway.posteditemendpoint.model.PostedItem content) throws java.io.IOException {
    InsertPostedItem result = new InsertPostedItem(content);
    initialize(result);
    return result;
  }

  public class InsertPostedItem extends PosteditemendpointRequest<com.example.giveaway.posteditemendpoint.model.PostedItem> {

    private static final String REST_PATH = "posteditem";

    /**
     * Create a request for the method "insertPostedItem".
     *
     * This request holds the parameters needed by the the posteditemendpoint server.  After setting
     * any optional parameters, call the {@link InsertPostedItem#execute()} method to invoke the
     * remote operation. <p> {@link InsertPostedItem#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.example.giveaway.posteditemendpoint.model.PostedItem}
     * @since 1.13
     */
    protected InsertPostedItem(com.example.giveaway.posteditemendpoint.model.PostedItem content) {
      super(Posteditemendpoint.this, "POST", REST_PATH, content, com.example.giveaway.posteditemendpoint.model.PostedItem.class);
    }

    @Override
    public InsertPostedItem setAlt(java.lang.String alt) {
      return (InsertPostedItem) super.setAlt(alt);
    }

    @Override
    public InsertPostedItem setFields(java.lang.String fields) {
      return (InsertPostedItem) super.setFields(fields);
    }

    @Override
    public InsertPostedItem setKey(java.lang.String key) {
      return (InsertPostedItem) super.setKey(key);
    }

    @Override
    public InsertPostedItem setOauthToken(java.lang.String oauthToken) {
      return (InsertPostedItem) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPostedItem setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPostedItem) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPostedItem setQuotaUser(java.lang.String quotaUser) {
      return (InsertPostedItem) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPostedItem setUserIp(java.lang.String userIp) {
      return (InsertPostedItem) super.setUserIp(userIp);
    }

    @Override
    public InsertPostedItem set(String parameterName, Object value) {
      return (InsertPostedItem) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPostedItem".
   *
   * This request holds the parameters needed by the the posteditemendpoint server.  After setting any
   * optional parameters, call the {@link ListPostedItem#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPostedItem listPostedItem() throws java.io.IOException {
    ListPostedItem result = new ListPostedItem();
    initialize(result);
    return result;
  }

  public class ListPostedItem extends PosteditemendpointRequest<com.example.giveaway.posteditemendpoint.model.CollectionResponsePostedItem> {

    private static final String REST_PATH = "posteditem";

    /**
     * Create a request for the method "listPostedItem".
     *
     * This request holds the parameters needed by the the posteditemendpoint server.  After setting
     * any optional parameters, call the {@link ListPostedItem#execute()} method to invoke the remote
     * operation. <p> {@link ListPostedItem#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPostedItem() {
      super(Posteditemendpoint.this, "GET", REST_PATH, null, com.example.giveaway.posteditemendpoint.model.CollectionResponsePostedItem.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPostedItem setAlt(java.lang.String alt) {
      return (ListPostedItem) super.setAlt(alt);
    }

    @Override
    public ListPostedItem setFields(java.lang.String fields) {
      return (ListPostedItem) super.setFields(fields);
    }

    @Override
    public ListPostedItem setKey(java.lang.String key) {
      return (ListPostedItem) super.setKey(key);
    }

    @Override
    public ListPostedItem setOauthToken(java.lang.String oauthToken) {
      return (ListPostedItem) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPostedItem setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPostedItem) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPostedItem setQuotaUser(java.lang.String quotaUser) {
      return (ListPostedItem) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPostedItem setUserIp(java.lang.String userIp) {
      return (ListPostedItem) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPostedItem setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPostedItem setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPostedItem set(String parameterName, Object value) {
      return (ListPostedItem) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePostedItem".
   *
   * This request holds the parameters needed by the the posteditemendpoint server.  After setting any
   * optional parameters, call the {@link RemovePostedItem#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePostedItem removePostedItem(java.lang.Long id) throws java.io.IOException {
    RemovePostedItem result = new RemovePostedItem(id);
    initialize(result);
    return result;
  }

  public class RemovePostedItem extends PosteditemendpointRequest<Void> {

    private static final String REST_PATH = "posteditem/{id}";

    /**
     * Create a request for the method "removePostedItem".
     *
     * This request holds the parameters needed by the the posteditemendpoint server.  After setting
     * any optional parameters, call the {@link RemovePostedItem#execute()} method to invoke the
     * remote operation. <p> {@link RemovePostedItem#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePostedItem(java.lang.Long id) {
      super(Posteditemendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePostedItem setAlt(java.lang.String alt) {
      return (RemovePostedItem) super.setAlt(alt);
    }

    @Override
    public RemovePostedItem setFields(java.lang.String fields) {
      return (RemovePostedItem) super.setFields(fields);
    }

    @Override
    public RemovePostedItem setKey(java.lang.String key) {
      return (RemovePostedItem) super.setKey(key);
    }

    @Override
    public RemovePostedItem setOauthToken(java.lang.String oauthToken) {
      return (RemovePostedItem) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePostedItem setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePostedItem) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePostedItem setQuotaUser(java.lang.String quotaUser) {
      return (RemovePostedItem) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePostedItem setUserIp(java.lang.String userIp) {
      return (RemovePostedItem) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePostedItem setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePostedItem set(String parameterName, Object value) {
      return (RemovePostedItem) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePostedItem".
   *
   * This request holds the parameters needed by the the posteditemendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePostedItem#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.giveaway.posteditemendpoint.model.PostedItem}
   * @return the request
   */
  public UpdatePostedItem updatePostedItem(com.example.giveaway.posteditemendpoint.model.PostedItem content) throws java.io.IOException {
    UpdatePostedItem result = new UpdatePostedItem(content);
    initialize(result);
    return result;
  }

  public class UpdatePostedItem extends PosteditemendpointRequest<com.example.giveaway.posteditemendpoint.model.PostedItem> {

    private static final String REST_PATH = "posteditem";

    /**
     * Create a request for the method "updatePostedItem".
     *
     * This request holds the parameters needed by the the posteditemendpoint server.  After setting
     * any optional parameters, call the {@link UpdatePostedItem#execute()} method to invoke the
     * remote operation. <p> {@link UpdatePostedItem#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.example.giveaway.posteditemendpoint.model.PostedItem}
     * @since 1.13
     */
    protected UpdatePostedItem(com.example.giveaway.posteditemendpoint.model.PostedItem content) {
      super(Posteditemendpoint.this, "PUT", REST_PATH, content, com.example.giveaway.posteditemendpoint.model.PostedItem.class);
    }

    @Override
    public UpdatePostedItem setAlt(java.lang.String alt) {
      return (UpdatePostedItem) super.setAlt(alt);
    }

    @Override
    public UpdatePostedItem setFields(java.lang.String fields) {
      return (UpdatePostedItem) super.setFields(fields);
    }

    @Override
    public UpdatePostedItem setKey(java.lang.String key) {
      return (UpdatePostedItem) super.setKey(key);
    }

    @Override
    public UpdatePostedItem setOauthToken(java.lang.String oauthToken) {
      return (UpdatePostedItem) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePostedItem setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePostedItem) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePostedItem setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePostedItem) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePostedItem setUserIp(java.lang.String userIp) {
      return (UpdatePostedItem) super.setUserIp(userIp);
    }

    @Override
    public UpdatePostedItem set(String parameterName, Object value) {
      return (UpdatePostedItem) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Posteditemendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Posteditemendpoint}. */
    @Override
    public Posteditemendpoint build() {
      return new Posteditemendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PosteditemendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPosteditemendpointRequestInitializer(
        PosteditemendpointRequestInitializer posteditemendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(posteditemendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
